version: "3.8"

services:
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGPORT=${POSTGRES_PORT}
    networks:
      - mimirror-server
    restart: unless-stopped
    mem_limit: 2g
    memswap_limit: 2g
    cpus: 2
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./docker-dev
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - mimirror-server
    restart: "on-failure"
    mem_limit: 2g
    memswap_limit: 2g
    cpus: 2
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy

networks:
  mimirror-server:
    driver: bridge

volumes:
  postgres_data:
